FROM php:8.3.8-fpm-alpine

ENV APACHE_SSL=1

RUN apk update \
    && apk add --no-cache \
        php-pgsql \
        php-intl \
        unzip \
        curl \
        bash \
        $PHPIZE_DEPS \
        linux-headers

# Télécharger le CLI Symfony et le rendre exécutable
RUN curl -sS https://get.symfony.com/cli/installer | bash
RUN mv /root/.symfony5/bin/symfony /usr/local/bin/symfony

WORKDIR /app

VOLUME /app/var/

# Installer Xdebug, spécifier une version compatible si nécessaire
RUN pecl install xdebug-3.3.2 \
    && docker-php-ext-enable xdebug \
    && echo "zend_extension=xdebug.so" > /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.mode=develop,debug,coverage" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini